### ISSUE TITLE
GS Tap

### ISSUE THREAD

**Issue by gajju3588** [cwensel/cascading-local#4]
Not an issue.

Is there any plan to support Google File system as well? Files with adress : gs://gajendra/test

**Comment by cwensel** [comment]
If Hadoop supports gs:// then Cascading supports it. Just know the support may not ship native in Hadoop, but may need to be added to your project or cluster.

See: https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage

If you want to access gs:// from Cascading Local mode, you need to use the cascading.tap.local.hadoop.LocalHfsAdaptor class in Cascading 4.

**Comment by cwensel** [comment]
Closing as this was also asked on the mail-list.
